import { FAMILY, TOOLS_LIMIT } from './consts';
import type { ModelDefinition, ReasoningEffort, ThinkingCapability } from './types';

/**
 * Standard capability set for OpenAI-compatible reasoning models served by
 * Command Code: tool calling enabled, no native vision unless the underlying
 * model supports it (annotated per-entry below), and a 4-level thinking
 * effort selector.
 */
const THINKING: ThinkingCapability = {
	supportedEfforts: ['low', 'medium', 'high'] as const,
	defaultEffort: 'medium' as ReasoningEffort,
	canDisable: true,
};

const NO_THINKING = false;

/**
 * Compile-time model registry. Mirrors the catalog exposed by Command Code.
 *
 * Each entry uses the upstream `vendor/name` slug from `cmdc --list-models`
 * as the model id. Copilot Chat receives the same id; users who route
 * through a custom base URL can remap them via `modelIdOverrides`.
 *
 * Vision-capable models are flagged with `imageInput: true`. Tool calling
 * is assumed to be supported for every model — adjust per-entry if a
 * specific upstream omits it.
 *
 * Token windows: `maxInputTokens` is the upstream `context_length` (the
 * total window, input + output) minus `maxOutputTokens`, which is reserved
 * for generation. This keeps the picker's input+output readout equal to the
 * real context window. The live catalog sync (`provider/catalog.ts`)
 * overrides these values from `GET /provider/v1/models` once an API key is
 * set, so the registry is the seed/fallback.
 */

export const MODELS: ModelDefinition[] = [
	// ---- Alibaba ----
	{
		id: 'Qwen/Qwen3.6-Max-Preview',
		name: 'Qwen 3.6 Max Preview',
		family: FAMILY,
		version: '3.6',
		detail: 'vibe coding & efficient agent execution',
		maxInputTokens: 168000,
		maxOutputTokens: 32000,
		capabilities: { toolCalling: TOOLS_LIMIT, imageInput: false, thinking: THINKING },
		category: 'Alibaba',
	},
	{
		id: 'Qwen/Qwen3.6-Plus',
		name: 'Qwen 3.6 Plus',
		family: FAMILY,
		version: '3.6',
		detail: 'agentic coding & reasoning',
		maxInputTokens: 168000,
		maxOutputTokens: 32000,
		capabilities: { toolCalling: TOOLS_LIMIT, imageInput: true, thinking: THINKING },
		category: 'Alibaba',
	},
	{
		id: 'Qwen/Qwen3.7-Flash',
		name: 'Qwen 3.7 Flash',
		family: FAMILY,
		version: '3.7',
		detail: 'fast low-cost agentic coding & reasoning',
		maxInputTokens: 968000,
		maxOutputTokens: 32000,
		capabilities: { toolCalling: TOOLS_LIMIT, imageInput: true, thinking: THINKING },
		category: 'Alibaba',
	},
	{
		id: 'Qwen/Qwen3.7-Max',
		name: 'Qwen 3.7 Max',
		family: FAMILY,
		version: '3.7',
		detail: 'frontier coding & long-horizon agent execution',
		maxInputTokens: 968000,
		maxOutputTokens: 32000,
		capabilities: { toolCalling: TOOLS_LIMIT, imageInput: false, thinking: THINKING },
		category: 'Alibaba',
	},
	{
		id: 'Qwen/Qwen3.7-Plus',
		name: 'Qwen 3.7 Plus',
		family: FAMILY,
		version: '3.7',
		detail: 'agentic coding & reasoning at lower cost',
		maxInputTokens: 968000,
		maxOutputTokens: 32000,
		capabilities: { toolCalling: TOOLS_LIMIT, imageInput: true, thinking: THINKING },
		category: 'Alibaba',
	},
	{
		id: 'Qwen/Qwen3.8-Max',
		name: 'Qwen 3.8 Max',
		family: FAMILY,
		version: '3.8',
		detail: 'autonomous long-horizon coding & professional work',
		maxInputTokens: 968000,
		maxOutputTokens: 32000,
		capabilities: { toolCalling: TOOLS_LIMIT, imageInput: true, thinking: THINKING },
		category: 'Alibaba',
	},
	{
		id: 'Qwen/Qwen3.8-Max-0902',
		name: 'Qwen 3.8 Max 0902',
		family: FAMILY,
		version: '3.8',
		detail: 'refreshed Qwen 3.8 Max for autonomous long-horizon coding',
		maxInputTokens: 968000,
		maxOutputTokens: 32000,
		capabilities: { toolCalling: TOOLS_LIMIT, imageInput: true, thinking: THINKING },
		category: 'Alibaba',
	},
	{
		id: 'Qwen/Qwen3.8-27B',
		name: 'Qwen 3.8 27B',
		family: FAMILY,
		version: '3.8',
		detail: 'cost-efficient 27B vision & reasoning',
		maxInputTokens: 230144,
		maxOutputTokens: 32000,
		capabilities: { toolCalling: TOOLS_LIMIT, imageInput: true, thinking: THINKING },
		category: 'Alibaba',
	},
	{
		id: 'Qwen/Qwen3.8-Flash',
		name: 'Qwen 3.8 Flash',
		family: FAMILY,
		version: '3.8',
		detail: 'fast low-cost agentic coding & reasoning',
		maxInputTokens: 968000,
		maxOutputTokens: 32000,
		capabilities: { toolCalling: TOOLS_LIMIT, imageInput: true, thinking: THINKING },
		category: 'Alibaba',
	},

	// ---- Anthropic ----
	{
		id: 'claude-fable-5',
		name: 'Claude Fable 5',
		family: FAMILY,
		version: 'fable-5',
		detail: 'most capable for demanding reasoning & long-horizon agents',
		maxInputTokens: 936000,
		maxOutputTokens: 64000,
		capabilities: { toolCalling: TOOLS_LIMIT, imageInput: true, thinking: THINKING },
		category: 'Anthropic',
	},
	{
		id: 'claude-fable-5-1',
		name: 'Claude Fable 5.1',
		family: FAMILY,
		version: 'fable-5-1',
		detail: 'latest Fable for demanding reasoning & long-horizon agents',
		maxInputTokens: 936000,
		maxOutputTokens: 64000,
		capabilities: { toolCalling: TOOLS_LIMIT, imageInput: true, thinking: THINKING },
		category: 'Anthropic',
	},
	{
		id: 'claude-haiku-4-5-20251001',
		name: 'Claude Haiku 4.5',
		family: FAMILY,
		version: 'haiku-4-5',
		detail: 'fastest & most compact, great for quick tasks',
		maxInputTokens: 136000,
		maxOutputTokens: 64000,
		capabilities: { toolCalling: TOOLS_LIMIT, imageInput: true, thinking: NO_THINKING },
		category: 'Anthropic',
	},
	{
		id: 'claude-opus-4-7',
		name: 'Claude Opus 4.7',
		family: FAMILY,
		version: 'opus-4-7',
		detail: 'older Opus, still strong for agents and coding',
		maxInputTokens: 968000,
		maxOutputTokens: 32000,
		capabilities: { toolCalling: TOOLS_LIMIT, imageInput: true, thinking: THINKING },
		category: 'Anthropic',
	},
	{
		id: 'claude-opus-4-8',
		name: 'Claude Opus 4.8',
		family: FAMILY,
		version: 'opus-4-8',
		detail: 'prev flagship, still strong for agents and coding',
		maxInputTokens: 968000,
		maxOutputTokens: 32000,
		capabilities: { toolCalling: TOOLS_LIMIT, imageInput: true, thinking: THINKING },
		category: 'Anthropic',
	},
	{
		id: 'claude-opus-5',
		name: 'Claude Opus 5',
		family: FAMILY,
		version: 'opus-5',
		detail: 'most intelligent Opus for agents and coding',
		maxInputTokens: 936000,
		maxOutputTokens: 64000,
		capabilities: { toolCalling: TOOLS_LIMIT, imageInput: true, thinking: THINKING },
		category: 'Anthropic',
	},
	{
		id: 'claude-sonnet-4-6',
		name: 'Claude Sonnet 4.6',
		family: FAMILY,
		version: 'sonnet-4-6',
		detail: 'prev Sonnet, still fast & capable',
		maxInputTokens: 936000,
		maxOutputTokens: 64000,
		capabilities: { toolCalling: TOOLS_LIMIT, imageInput: true, thinking: NO_THINKING },
		category: 'Anthropic',
	},
	{
		id: 'claude-sonnet-5',
		name: 'Claude Sonnet 5',
		family: FAMILY,
		version: 'sonnet-5',
		detail: 'best combo of speed & intelligence (recommended)',
		maxInputTokens: 936000,
		maxOutputTokens: 64000,
		capabilities: { toolCalling: TOOLS_LIMIT, imageInput: true, thinking: THINKING },
		category: 'Anthropic',
	},

	// ---- DeepSeek ----
	{
		id: 'deepseek/deepseek-v4-flash',
		name: 'DeepSeek V4 Flash',
		family: FAMILY,
		version: 'v4',
		detail: 'fast hybrid-attention reasoning',
		maxInputTokens: 968000,
		maxOutputTokens: 32000,
		capabilities: { toolCalling: TOOLS_LIMIT, imageInput: false, thinking: THINKING },
		category: 'DeepSeek',
	},
	{
		id: 'deepseek/deepseek-v4-flash-fast',
		name: 'DeepSeek V4 Flash Fast',
		family: FAMILY,
		version: 'v4',
		detail: 'ultra-fast low-cost hybrid-attention reasoning',
		maxInputTokens: 968000,
		maxOutputTokens: 32000,
		capabilities: { toolCalling: TOOLS_LIMIT, imageInput: false, thinking: THINKING },
		category: 'DeepSeek',
	},
	{
		id: 'deepseek/deepseek-v4-flash-vision-exp',
		name: 'DeepSeek V4 Flash Vision (exp)',
		family: FAMILY,
		version: 'v4',
		detail: 'fast hybrid-attention reasoning with vision input',
		maxInputTokens: 968000,
		maxOutputTokens: 32000,
		capabilities: { toolCalling: TOOLS_LIMIT, imageInput: true, thinking: THINKING },
		category: 'DeepSeek',
	},
	{
		id: 'deepseek/deepseek-v4-pro',
		name: 'DeepSeek V4 Pro',
		family: FAMILY,
		version: 'v4',
		detail: 'hybrid-attention long-context reasoning',
		maxInputTokens: 968000,
		maxOutputTokens: 32000,
		capabilities: { toolCalling: TOOLS_LIMIT, imageInput: false, thinking: THINKING },
		category: 'DeepSeek',
	},
	{
		id: 'deepseek/deepseek-v4.1-flash',
		name: 'DeepSeek V4.1 Flash',
		family: FAMILY,
		version: 'v4.1',
		detail: 'hybrid-attention reasoning with vision',
		// 1M total context window (1000000) minus 32K reserved for output.
		maxInputTokens: 968000,
		maxOutputTokens: 32000,
		capabilities: { toolCalling: TOOLS_LIMIT, imageInput: true, thinking: THINKING },
		category: 'DeepSeek',
	},

	// ---- Google ----
	{
		id: 'google/gemini-3.1-flash-lite',
		name: 'Gemini 3.1 Flash Lite',
		family: FAMILY,
		version: '3.1',
		detail: 'high-volume workhorse model with implicit caching',
		maxInputTokens: 936000,
		maxOutputTokens: 64000,
		capabilities: { toolCalling: TOOLS_LIMIT, imageInput: true, thinking: THINKING },
		category: 'Google',
	},
	{
		id: 'google/gemini-3.5-flash',
		name: 'Gemini 3.5 Flash',
		family: FAMILY,
		version: '3.5',
		detail: 'Pro-level coding proficiency, parallel agentic execution',
		maxInputTokens: 936000,
		maxOutputTokens: 64000,
		capabilities: { toolCalling: TOOLS_LIMIT, imageInput: true, thinking: THINKING },
		category: 'Google',
	},
	{
		id: 'google/gemini-3.5-flash-lite',
		name: 'Gemini 3.5 Flash Lite',
		family: FAMILY,
		version: '3.5',
		detail: 'upgraded agentic capabilities, ideal for subagents',
		maxInputTokens: 936000,
		maxOutputTokens: 64000,
		capabilities: { toolCalling: TOOLS_LIMIT, imageInput: true, thinking: THINKING },
		category: 'Google',
	},
	{
		id: 'google/gemini-3.6-flash',
		name: 'Gemini 3.6 Flash',
		family: FAMILY,
		version: '3.6',
		detail: 'previous Gemini Flash, still fast & capable',
		maxInputTokens: 936000,
		maxOutputTokens: 64000,
		capabilities: { toolCalling: TOOLS_LIMIT, imageInput: true, thinking: THINKING },
		category: 'Google',
	},
	{
		id: 'google/gemini-3.7-flash',
		name: 'Gemini 3.7 Flash',
		family: FAMILY,
		version: '3.7',
		detail: 'higher-quality coding & agentic workflows, fewer tokens',
		maxInputTokens: 984576,
		maxOutputTokens: 64000,
		capabilities: { toolCalling: TOOLS_LIMIT, imageInput: true, thinking: THINKING },
		category: 'Google',
	},
	{
		id: 'google/gemini-3.8-flash',
		name: 'Gemini 3.8 Flash',
		family: FAMILY,
		version: '3.8',
		detail: 'latest Gemini Flash for fast coding & agentic workflows',
		maxInputTokens: 936000,
		maxOutputTokens: 64000,
		capabilities: { toolCalling: TOOLS_LIMIT, imageInput: true, thinking: THINKING },
		category: 'Google',
	},

	// ---- Meituan ----
	{
		id: 'meituan/LongCat-2.0:free',
		name: 'LongCat 2.0 (free)',
		family: FAMILY,
		version: '2.0',
		detail: 'free long-context reasoning',
		// 1M total context window (1048576) minus 32K reserved for output.
		maxInputTokens: 1016576,
		maxOutputTokens: 32000,
		capabilities: { toolCalling: TOOLS_LIMIT, imageInput: false, thinking: THINKING },
		category: 'Meituan',
	},

	// ---- Meta ----
	{
		id: 'meta/muse-spark-1.1',
		name: 'Muse Spark 1.1',
		family: FAMILY,
		version: '1.1',
		detail: 'agentic performance, tool use, and computer use',
		// 1M total context window (1048576) minus 128K reserved for output.
		maxInputTokens: 917504,
		maxOutputTokens: 131072,
		capabilities: { toolCalling: TOOLS_LIMIT, imageInput: true, thinking: THINKING },
		category: 'Meta',
	},
	{
		id: 'meta/muse-spark-1.2',
		name: 'Muse Spark 1.2',
		family: FAMILY,
		version: '1.2',
		detail: 'coding-optimized for agentic workflows and large codebases',
		// 1M total context window (1048576) minus 128K reserved for output.
		maxInputTokens: 917504,
		maxOutputTokens: 131072,
		capabilities: { toolCalling: TOOLS_LIMIT, imageInput: true, thinking: THINKING },
		category: 'Meta',
	},
	{
		id: 'meta/muse-spark-1.2-contributor',
		name: 'Muse Spark 1.2 Contributor',
		family: FAMILY,
		version: '1.2',
		detail: 'Muse Spark 1.2 at ~95% off',
		// 1M total context window (1048576) minus 128K reserved for output.
		maxInputTokens: 917504,
		maxOutputTokens: 131072,
		capabilities: { toolCalling: TOOLS_LIMIT, imageInput: true, thinking: THINKING },
		category: 'Meta',
	},
	{
		id: 'meta/muse-spark-1.3',
		name: 'Muse Spark 1.3',
		family: FAMILY,
		version: '1.3',
		detail: 'latest open agentic model for coding & long-horizon workflows',
		// 1M total context window (1048576) minus 128K reserved for output.
		maxInputTokens: 917504,
		maxOutputTokens: 131072,
		capabilities: { toolCalling: TOOLS_LIMIT, imageInput: true, thinking: THINKING },
		category: 'Meta',
	},
	{
		id: 'meta/muse-spark-1.3-contributor',
		name: 'Muse Spark 1.3 Contributor',
		family: FAMILY,
		version: '1.3',
		detail: 'Muse Spark 1.3 at ~95% off',
		// 1M total context window (1048576) minus 128K reserved for output.
		maxInputTokens: 917504,
		maxOutputTokens: 131072,
		capabilities: { toolCalling: TOOLS_LIMIT, imageInput: true, thinking: THINKING },
		category: 'Meta',
	},

	// ---- MiniMax ----
	{
		id: 'MiniMaxAI/MiniMax-M2.5',
		name: 'MiniMax M2.5',
		family: FAMILY,
		version: 'm2.5',
		detail: 'cross-platform full-stack agentic dev',
		maxInputTokens: 168000,
		maxOutputTokens: 32000,
		capabilities: { toolCalling: TOOLS_LIMIT, imageInput: false, thinking: NO_THINKING },
		category: 'MiniMax',
	},
	{
		id: 'MiniMaxAI/MiniMax-M2.7',
		name: 'MiniMax M2.7',
		family: FAMILY,
		version: 'm2.7',
		detail: 'end-to-end software engineering agent',
		maxInputTokens: 168000,
		maxOutputTokens: 32000,
		capabilities: { toolCalling: TOOLS_LIMIT, imageInput: false, thinking: NO_THINKING },
		category: 'MiniMax',
	},
	{
		id: 'MiniMaxAI/MiniMax-M3',
		name: 'MiniMax M3',
		family: FAMILY,
		version: 'm3',
		detail: 'frontier coding, agents & native multimodality',
		maxInputTokens: 968000,
		maxOutputTokens: 32000,
		capabilities: { toolCalling: TOOLS_LIMIT, imageInput: true, thinking: THINKING },
		category: 'MiniMax',
	},

	// ---- Moonshot AI ----
	{
		id: 'moonshotai/Kimi-K2.5',
		name: 'Kimi K2.5',
		family: FAMILY,
		version: 'k2.5',
		detail: 'multimodal frontend coding',
		maxInputTokens: 224000,
		maxOutputTokens: 32000,
		capabilities: { toolCalling: TOOLS_LIMIT, imageInput: true, thinking: NO_THINKING },
		category: 'Moonshot AI',
	},
	{
		id: 'moonshotai/Kimi-K2.6',
		name: 'Kimi K2.6',
		family: FAMILY,
		version: 'k2.6',
		detail: 'long-horizon coding with vision',
		maxInputTokens: 224000,
		maxOutputTokens: 32000,
		capabilities: { toolCalling: TOOLS_LIMIT, imageInput: true, thinking: NO_THINKING },
		category: 'Moonshot AI',
	},
	{
		id: 'moonshotai/Kimi-K2.7-Code',
		name: 'Kimi K2.7 Code',
		family: FAMILY,
		version: 'k2.7',
		detail: 'improved long-horizon coding with vision',
		maxInputTokens: 224000,
		maxOutputTokens: 32000,
		capabilities: { toolCalling: TOOLS_LIMIT, imageInput: true, thinking: THINKING },
		category: 'Moonshot AI',
	},
	{
		id: 'moonshotai/Kimi-K2.7-Code-Highspeed',
		name: 'Kimi K2.7 Code HighSpeed',
		family: FAMILY,
		version: 'k2.7',
		detail: 'high-speed long-horizon coding with vision',
		maxInputTokens: 230000,
		maxOutputTokens: 32000,
		capabilities: { toolCalling: TOOLS_LIMIT, imageInput: true, thinking: THINKING },
		category: 'Moonshot AI',
	},
	{
		id: 'moonshotai/Kimi-K3',
		name: 'Kimi K3',
		family: FAMILY,
		version: 'k3',
		detail: 'long-horizon coding & knowledge work with 1M context',
		maxInputTokens: 968000,
		maxOutputTokens: 32000,
		capabilities: { toolCalling: TOOLS_LIMIT, imageInput: true, thinking: THINKING },
		category: 'Moonshot AI',
	},

	// ---- NVIDIA ----
	{
		id: 'nvidia/nemotron-3-ultra-550b-a55b',
		name: 'Nemotron 3 Ultra',
		family: FAMILY,
		version: '3',
		detail: 'open reasoning model for long-horizon autonomous agents',
		maxInputTokens: 968000,
		maxOutputTokens: 32000,
		capabilities: { toolCalling: TOOLS_LIMIT, imageInput: false, thinking: THINKING },
		category: 'NVIDIA',
	},

	// ---- OpenAI ----
	{
		id: 'gpt-5.3-codex',
		name: 'GPT-5.3 Codex',
		family: FAMILY,
		version: '5.3',
		detail: 'frontier coding model',
		maxInputTokens: 368000,
		maxOutputTokens: 32000,
		capabilities: { toolCalling: TOOLS_LIMIT, imageInput: true, thinking: THINKING },
		category: 'OpenAI',
	},
	{
		id: 'gpt-5.4',
		name: 'GPT-5.4',
		family: FAMILY,
		version: '5.4',
		detail: 'frontier model for general complex work',
		maxInputTokens: 368000,
		maxOutputTokens: 32000,
		capabilities: { toolCalling: TOOLS_LIMIT, imageInput: true, thinking: THINKING },
		category: 'OpenAI',
	},
	{
		id: 'gpt-5.4-mini',
		name: 'GPT-5.4 Mini',
		family: FAMILY,
		version: '5.4',
		detail: 'fast, cost-effective model for everyday tasks',
		maxInputTokens: 368000,
		maxOutputTokens: 32000,
		capabilities: { toolCalling: TOOLS_LIMIT, imageInput: true, thinking: THINKING },
		category: 'OpenAI',
	},
	{
		id: 'gpt-5.5',
		name: 'GPT-5.5',
		family: FAMILY,
		version: '5.5',
		detail: 'latest frontier model for general complex work',
		maxInputTokens: 168000,
		maxOutputTokens: 32000,
		capabilities: { toolCalling: TOOLS_LIMIT, imageInput: true, thinking: THINKING },
		category: 'OpenAI',
	},
	{
		id: 'gpt-5.6-luna',
		name: 'GPT-5.6 Luna',
		family: FAMILY,
		version: '5.6',
		detail: 'optimized for cost-sensitive workloads',
		maxInputTokens: 1018000,
		maxOutputTokens: 32000,
		capabilities: { toolCalling: TOOLS_LIMIT, imageInput: true, thinking: THINKING },
		category: 'OpenAI',
	},
	{
		id: 'gpt-5.6-sol',
		name: 'GPT-5.6 Sol',
		family: FAMILY,
		version: '5.6',
		detail: 'frontier model for complex professional work',
		maxInputTokens: 1018000,
		maxOutputTokens: 32000,
		capabilities: { toolCalling: TOOLS_LIMIT, imageInput: true, thinking: THINKING },
		category: 'OpenAI',
	},
	{
		id: 'gpt-5.6-terra',
		name: 'GPT-5.6 Terra',
		family: FAMILY,
		version: '5.6',
		detail: 'balances intelligence and cost',
		maxInputTokens: 1018000,
		maxOutputTokens: 32000,
		capabilities: { toolCalling: TOOLS_LIMIT, imageInput: true, thinking: THINKING },
		category: 'OpenAI',
	},
	{
		id: 'gpt-6-astra',
		name: 'GPT-6 Astra',
		family: FAMILY,
		version: '6',
		detail: 'most capable OpenAI model for demanding reasoning & agents',
		// 1.05M total context window (1050000) minus 32K reserved for output.
		maxInputTokens: 1018000,
		maxOutputTokens: 32000,
		capabilities: { toolCalling: TOOLS_LIMIT, imageInput: true, thinking: THINKING },
		category: 'OpenAI',
	},

	// ---- Poolside ----
	{
		id: 'poolside/laguna-s-2.1-free',
		name: 'Laguna S 2.1',
		family: FAMILY,
		version: '2.1',
		detail: 'open-weight agentic coding and long-horizon work',
		maxInputTokens: 224000,
		maxOutputTokens: 32000,
		capabilities: { toolCalling: TOOLS_LIMIT, imageInput: false, thinking: THINKING },
		category: 'Poolside',
	},

	// ---- Sakana AI ----
	{
		id: 'sakana/fugu-ultra',
		name: 'Fugu Ultra',
		family: FAMILY,
		version: 'ultra',
		detail: 'multi-agent orchestration across frontier models',
		maxInputTokens: 968000,
		maxOutputTokens: 32000,
		capabilities: { toolCalling: TOOLS_LIMIT, imageInput: true, thinking: THINKING },
		category: 'Sakana AI',
	},

	// ---- StepFun ----
	{
		id: 'stepfun/Step-3.5-Flash',
		name: 'Step 3.5 Flash',
		family: FAMILY,
		version: '3.5',
		detail: 'fast sparse-MoE agentic reasoning',
		maxInputTokens: 968000,
		maxOutputTokens: 32000,
		capabilities: { toolCalling: TOOLS_LIMIT, imageInput: false, thinking: THINKING },
		category: 'StepFun',
	},
	{
		id: 'stepfun/Step-3.7-Flash',
		name: 'Step 3.7 Flash',
		family: FAMILY,
		version: '3.7',
		detail: 'multimodal sparse-MoE reasoning',
		maxInputTokens: 224000,
		maxOutputTokens: 32000,
		capabilities: { toolCalling: TOOLS_LIMIT, imageInput: true, thinking: THINKING },
		category: 'StepFun',
	},

	// ---- Tencent ----
	{
		id: 'tencent/hy3-paid',
		name: 'Tencent Hy3',
		family: FAMILY,
		version: 'hy3',
		detail: 'sparse-MoE reasoning & agentic tool use',
		maxInputTokens: 230144,
		maxOutputTokens: 32000,
		capabilities: { toolCalling: TOOLS_LIMIT, imageInput: false, thinking: THINKING },
		category: 'Tencent',
	},

	// ---- Thinking Machines ----
	{
		id: 'thinkingmachines/inkling',
		name: 'Inkling',
		family: FAMILY,
		version: 'inkling',
		detail: 'multimodal MoE reasoning',
		maxInputTokens: 224000,
		maxOutputTokens: 32000,
		capabilities: { toolCalling: TOOLS_LIMIT, imageInput: true, thinking: THINKING },
		category: 'Thinking Machines',
	},
	{
		id: 'thinkingmachines/inkling-small',
		name: 'Inkling Small',
		family: FAMILY,
		version: 'inkling',
		detail: 'lightweight MoE reasoning at lower cost and latency',
		maxInputTokens: 968000,
		maxOutputTokens: 32000,
		capabilities: { toolCalling: TOOLS_LIMIT, imageInput: true, thinking: THINKING },
		category: 'Thinking Machines',
	},

	// ---- xAI ----
	{
		id: 'xai/grok-4.5',
		name: 'Grok 4.5',
		family: FAMILY,
		version: '4.5',
		detail: 'smartest model for coding, agentic tasks, knowledge work',
		maxInputTokens: 468000,
		maxOutputTokens: 32000,
		capabilities: { toolCalling: TOOLS_LIMIT, imageInput: true, thinking: THINKING },
		category: 'xAI',
	},
	{
		id: 'xai/grok-4.6',
		name: 'Grok 4.6',
		family: FAMILY,
		version: '4.6',
		detail: 'frontier performance on coding, knowledge work, and STEM',
		maxInputTokens: 468000,
		maxOutputTokens: 32000,
		capabilities: { toolCalling: TOOLS_LIMIT, imageInput: false, thinking: THINKING },
		category: 'xAI',
	},

	// ---- Xiaomi ----
	{
		id: 'xiaomi/mimo-v2.5',
		name: 'MiMo V2.5',
		family: FAMILY,
		version: 'v2.5',
		detail: 'efficient long-context agentic coding',
		maxInputTokens: 968000,
		maxOutputTokens: 32000,
		capabilities: { toolCalling: TOOLS_LIMIT, imageInput: true, thinking: NO_THINKING },
		category: 'Xiaomi',
	},
	{
		id: 'xiaomi/mimo-v2.5-pro',
		name: 'MiMo V2.5 Pro',
		family: FAMILY,
		version: 'v2.5',
		detail: 'high-capability long-context agentic coding',
		maxInputTokens: 968000,
		maxOutputTokens: 32000,
		capabilities: { toolCalling: TOOLS_LIMIT, imageInput: false, thinking: NO_THINKING },
		category: 'Xiaomi',
	},

	// ---- Z AI ----
	{
		id: 'zai-org/GLM-5',
		name: 'GLM-5',
		family: FAMILY,
		version: '5',
		detail: 'multi-mode thinking & long-range planning',
		maxInputTokens: 168000,
		maxOutputTokens: 32000,
		capabilities: { toolCalling: TOOLS_LIMIT, imageInput: false, thinking: NO_THINKING },
		category: 'Z AI',
	},
	{
		id: 'zai-org/GLM-5.1',
		name: 'GLM-5.1',
		family: FAMILY,
		version: '5.1',
		detail: 'long-horizon autonomous coding agent',
		maxInputTokens: 168000,
		maxOutputTokens: 32000,
		capabilities: { toolCalling: TOOLS_LIMIT, imageInput: false, thinking: NO_THINKING },
		category: 'Z AI',
	},
	{
		id: 'zai-org/GLM-5.2',
		name: 'GLM-5.2',
		family: FAMILY,
		version: '5.2',
		detail: 'powerful coding with 1M context and long-horizon tasks',
		maxInputTokens: 968000,
		maxOutputTokens: 32000,
		capabilities: { toolCalling: TOOLS_LIMIT, imageInput: false, thinking: THINKING },
		category: 'Z AI',
	},
	{
		id: 'zai-org/GLM-5.2-Fast',
		name: 'GLM-5.2 Fast',
		family: FAMILY,
		version: '5.2',
		detail: 'high-throughput GLM-5.2 with 1M context',
		maxInputTokens: 968000,
		maxOutputTokens: 32000,
		capabilities: { toolCalling: TOOLS_LIMIT, imageInput: false, thinking: NO_THINKING },
		category: 'Z AI',
	},
	{
		id: 'zai-org/GLM-5.3',
		name: 'GLM-5.3',
		family: FAMILY,
		version: '5.3',
		detail: 'frontier coding with 1M context',
		maxInputTokens: 968000,
		maxOutputTokens: 32000,
		capabilities: { toolCalling: TOOLS_LIMIT, imageInput: false, thinking: THINKING },
		category: 'Z AI',
	},
	{
		id: 'z-ai/glm-5.3-flash',
		name: 'GLM-5.3 Flash',
		family: FAMILY,
		version: '5.3',
		detail: 'fast, affordable GLM coding with 1M context',
		// 1M total context window (1048576) minus 32K reserved for output.
		maxInputTokens: 1016576,
		maxOutputTokens: 32000,
		capabilities: { toolCalling: TOOLS_LIMIT, imageInput: true, thinking: THINKING },
		category: 'Z AI',
	},
];
